library/urls.py
from django.conf.urls import url
from . import views

app_name = 'library'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^book/(?P<pk>[0-9]+)/$', views.BookDetailView.as_view(), name='detail'),
    url(r'^alltags/', views.alltags, name='alltags'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^mybook/(?P<pk>[0-9]+)/$',views.MyBookView.as_view(),name='mybook'),
    url(r'^search/$', views.search, name='search'),
    url(r'^borrow/',views.borrow,name="borrow"),
]

libsys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path('',include('library.urls')),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
]

templates/alltags.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load lib_tags %}

                    {% block main %}
                    <div class="tag-cloud">
                    <ul >
                    {% for tag in tag_list %}
                    <li class="col-xs-6 col-lg-3">
                    <a href="{% url 'library:tag' tag.pk %}">{{ tag.name }}({{tag.num_books}})</a>
                    </li>
                    {% empty %}
                    暂无标签！
                    {% endfor %}
                    </ul>
                    </div>
                    {% endblock main %}

​

templates/base.html
{% load staticfiles %}
{% load lib_tags %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>图书管理系统V1.0</title>

    <!-- Bootstrap -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="{% static 'library/css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">图书管理系统</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'library:index' %}">图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class=><a href="{% url 'library:index' %}">主页</a></li>
            <li><a href="{% url 'library:alltags' %}">馆藏目录</a></li>
            {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" >我的图书馆<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'library:mybook' user.pk %}">已借书籍</a></li>
                <li><a href="#">到期书籍(未开发)</a></li>
                <li><a href="#">借阅历史(未开发)</a></li>
              </ul>
            </li>
             {% endif %} 

          </ul>
          
          <ul class="nav navbar-nav navbar-left ">
            <form class=" pull-right navbar-form col-md-6" role="search" method="get" id="searchform" action="{% url 'library:search' %}">

              <input type="search"  name="q" class="form-control" placeholder="Search" required>
            <button type="sumbit" class="btn btn-deafult">搜索</button>
            </form>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><p class="navbar-text">欢迎你:<span id="base_name">{{ user.username }}</span></p>
            <li><a href="{% url 'logout' %}">注销</a></li>
            <li><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a></li>
            {% else %}
            <li><a href="{% url 'users:register' %}">注册</a></li>
            <li><a href="{% url 'login' %}?next={{ request.path }}">登陆</a></li>
            {% endif %}

          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>
  <header class="jumbotron subhead" id="header-base">
      <div class="container">
          <h1>欢迎使用本图书管理系统(v1.0)<h1>
          <h3>知识改变命运</h3>
      </div>
  </header>
    <div class="container">
      <div class="row ">
        <div class="col-xs-12 col-sm-9">
          <div class="row">

            {% block main %} 
            {% endblock main %}
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->
            <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
                <div class="tag-cloud">
                <h3 class="tag-title">热门标签</h3>
                {% get_recent_tags as tag_list %}
                <ul>
                {% for tag in tag_list %}
                <li>
                <a href="{% url 'library:tag' tag.pk %}">{{ tag.name }}</a>
                </li>
                {% empty %}
                暂无标签！
                {% endfor %}
                </ul>
                </div>
            </div><!--/.sidebar-offcanvas-->

      </div><!--/row-->

      <hr>

      <footer>
        <p>© 2018 Wh1te | 保留一切权利</p>
      </footer>

    </div><!--/.container-->




    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </body>
</html>
​

templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

                    {% block main %}
        <div class="col-xs-12 col-sm-9 book book-{{ book.pk }}">
          <div class="row" >
            <div class="col-xs-6 col-lg-3">
            <img src="{{ book.cover_img}}" height="206" width="156">
            </div>
            <div class="col-xs-6 col-lg-9">
              <span>
                <span >书名:{{ book.title}} </span>
                </br>
                <span >作者:{{ book.author}} </span>
                </br>
                <span>出版社:{{ book.publisher}}</span>
                </br>
                <span>副标题: {{ book.subtitle}}</span>
                </br>
                <span>译者: {{ book.translator}}</span>
                </br>
                <span>出版年: {{ book.pubdate}}</span>
                </br>
                <span>页数: {{ book.pages}}</span>
                </br>
                <span>定价: {{ book.price}}</span>
                </br>
                <span>ISBN: {{ book.isbn}}</span>
                </br>
                <span>入库时间:{{ book.create_time}}</span>
                </br>
                <form  role="borrow" method="get" id="searchform" action="{% url 'library:borrow' %}">
                    <input type="hidden"  name="q"  value="{{ user.username }}">
                     <input type="hidden"  name="p"  value="{{book.title }}">
                <button type="sumbit" class="btn btn-primary">申请借书</button>
                </form>
              </span>
            </div>

          <div class=" col-xs-6 col-lg-12">
              <h3>内容简介:</h3>
              <p>{{ book.summary}}</p>
        </div>

          <div class="intro col-xs-6 col-lg-12">
              <h3>作者简介:</h3>
              <p>{{ book.author_intro}}</p>
          </div>
           {% endblock main %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
                    {% block main %}
                    {% if error_msg %}
                    <p>{{ error_msg }}</p>
                    {% endif %}
                    {% for book in book_list %}
                    <div class="col-xs-6 col-lg-4 book book-{{ book.pk }}">
                    <img src="{{ book.cover_img}}" height="354px" width="262px">
                    <h4>{{ book.title }}</h4>
                    <p>作者:{{ book.author }}</p>
                    <p><a class="btn btn-default" href="{{ book.get_absolute_url }}" role="button">查看此书详情</a></p>
                    </div><!--/.col-xs-6.col-lg-4-->
                    {% empty %}
                    <div class="no-book">暂时还没有入库的书籍！</div>
                    {% endfor %}
                    {% if is_paginated %}
                    <div class="pagination col-xs-6 col-lg-12">
                      {% if first %}
                        <a href="?page=1">1</a>
                      {% endif %}
                      {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                      {% endif %}
                      <a class="current-page" href="?page={{ page_obj.number }}" >{{ page_obj.number }}</a>
                      {% if right %}
                        {% for i in right %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                      {% endif %}
                      {% if last %}
                        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                      {% endif %}
                    </div>
                    {% endif %}
                    {% endblock main %}
​

templates/is_borrowed.html
{% extends 'base.html' %}
{% load staticfiles %}

                    {% block main %}
        <div class="col-xs-12 col-sm-9 current_book current_book-{{ current_book.pk }}">
          <div class="row" >
            <div class="col-xs-6 col-lg-3">
            <img src="{{ current_book.cover_img}}" height="206" width="156">
            </div>
            <div class="col-xs-6 col-lg-9">
              <span>
                <span >书名:{{ current_book.title}} </span>
                </br>
                <span >作者:{{ current_book.author}} </span>
                </br>
                <span>出版社:{{ current_book.publisher}}</span>
                </br>
                <span>副标题: {{ current_book.subtitle}}</span>
                </br>
                <span>译者: {{ current_book.translator}}</span>
                </br>
                <span>出版年: {{ current_book.pubdate}}</span>
                </br>
                <span>页数: {{ current_book.pages}}</span>
                </br>
                <span>定价: {{ current_book.price}}</span>
                </br>
                <span>ISBN: {{ current_book.isbn}}</span>
                </br>
                <span>入库时间:{{ current_book.create_time}}</span>
                <br>
                 {% if error_msg %}
                <span class="label label-danger">{{ error_msg }}</span>
                {% endif %}
              </span>
            </div>

          <div class=" col-xs-6 col-lg-12">
              <h3>内容简介:</h3>
              <p>{{ current_book.summary}}</p>
        </div>

          <div class="intro col-xs-6 col-lg-12">
              <h3>作者简介:</h3>
              <p>{{ current_book.author_intro}}</p>
          </div>
           {% endblock main %}